### ISSUE TITLE
SSH connection between mac & raspberry pi

### ISSUE THREAD

**Issue by NikhilJArora** [NikhilJArora/fydp-codebase#2]
Was able to establish connection and control over ssh via internet sharing using the Mac.

When the Mac is connected to a network that does not support internet sharing, the connection to the Pi cannot be held.  

Need to be able to some how connect to the Pi using an Ethernet connection and no network.

**Comment by NikhilJArora** [comment]
Links I used:
https://mycyberuniverse.com/mac-os/connect-to-raspberry-pi-from-a-mac-using-ethernet.html
https://www.raspberrypi.org/documentation/remote-access/ssh/unix.md

**Comment by alexkung1** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=15130

**Comment by NikhilJArora** [comment]
https://wiki.debian.org/WiFi/AdHoc @alexkung1

**Comment by alexkung1** [comment]
https://wiki.debian.org/WiFi/AdHoc

**Comment by alexkung1** [comment]
mission solved
